#! /bin/csh -f

# v0.2 - muheim - Mon Aug 24 10:44:37 CEST 2015
#  - set also the DRC/LVS setings in ".setPDK.csh" (rename)
# v0.1 - kgf - Fri Jan 16 10:46:27 CET 2015
#  - copy from smic v0.3, use the v6 icfii

## set the PDK_HOME for the pdk and the BEOL_STACK for the layerstack
#setenv PDK_HOME /usr/pack/global-28-kgf/gf/pdk-28SLP-V1.0_7.0/
source ../.setPDK.csh



## the variables to be set
#setenv CDS_Netlisting_Mode "Analog"
  # set it in the .cdsinit

#  setenv CDS_LOAD_ENV CWD
#
#          CWD:  loads only the ./.cdsenv
#        False: loads neither ~/.cdsenv nor ./.cdsenv
#       addCWD: loads ~/.cdsenv , then load ./.cdsenv
#  CWDElseHome: loads ./.cdsenv if it exists, or ~/.cdsenv , if it exists
setenv CDS_LOAD_ENV "CWDElseHome"

# This variable is used to make sure that the case is preserved
# when VHDL files are read by Verilog In. Otherwise there is sometimes
# a discrepancy between the VHDL file and the later resulting Verilog netlist
#setenv CDS_ALT_NMP match

# Calibre default runsets
#setenv MGC_CALIBRE_DRC_RUNSET_FILE "../calibre/drc/runset.drc"
#setenv MGC_CALIBRE_LVS_RUNSET_FILE "../calibre/lvs/runset.lvs"
#setenv MGC_CALIBRE_PEX_RUNSET_FILE "../calibre/pex/runset.pex"


## Determine the tool to startup 
switch ($1)
  case 615:
     set CDS = "cds_ic6-15.132 virtuoso"
     breaksw
  case 616:
     set CDS = "cds_ic6-16.030 virtuoso"
     breaksw
  case xterm
     set CDS = "cds_ic6-16.030 xterm"
     breaksw

## this is the command that runs as default, it can be adjusted to whatever you
## please
default:
     set CDS = "cds_ic6-16.030 virtuoso"
     breaksw
endsw  

##echo "Starting $CDS icfb"
$CDS icfb 
