#! /bin/csh -f

# v0.2 - muheim - Fri Aug 21 15:44:53 CEST 2015
#  - move the all the setings for calibre to the same seting file
#    used on dfii and calibre
# v0.1 - muheim - Wed Jan 21 09:46:02 CET 2015
#  - copy from umc65 adapt it o gf28

## set the relevant env for dfii and calibre
source ../.setPDK.csh

## Determine the tool to startup 
switch ($1)
  case 2015.3
     set CALIBRE = "calibre-2015.3 calibredrv -dl .init/gf28.layerprops"
     breaksw
  case xterm 
     set CALIBRE = "xterm" 
     breaksw
## this is the command that runs as default, it can be adjusted to whatever you
## please
default:
     set CALIBRE = "calibre-2015.3 calibredrv -dl .init/gf28.layerprops"
     breaksw
endsw  

##echo "Starting $CALIBRE"
$CALIBRE
